{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidymodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidymodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidymodels/tidymodels_{{ version }}.tar.gz
  sha256: 2472d17da0da8dae1a4fd392e1500c40bfccf09ed9f0491dc5954e414cb65d70

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=0.7.0
    - r-cli >=2.0.2
    - r-crayon >=1.3.4
    - r-dials >=0.0.8
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.3.2
    - r-infer >=0.5.2
    - r-magrittr >=1.5
    - r-modeldata >=0.0.2
    - r-parsnip >=0.1.2
    - r-purrr >=0.3.4
    - r-recipes >=0.1.13
    - r-rlang >=0.4.7
    - r-rsample >=0.0.7
    - r-rstudioapi >=0.11
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.0
    - r-tune >=0.1.1
    - r-workflows >=0.1.2
    - r-yardstick >=0.0.7
  run:
    - r-base
    - r-broom >=0.7.0
    - r-cli >=2.0.2
    - r-crayon >=1.3.4
    - r-dials >=0.0.8
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.3.2
    - r-infer >=0.5.2
    - r-magrittr >=1.5
    - r-modeldata >=0.0.2
    - r-parsnip >=0.1.2
    - r-purrr >=0.3.4
    - r-recipes >=0.1.13
    - r-rlang >=0.4.7
    - r-rsample >=0.0.7
    - r-rstudioapi >=0.11
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.0
    - r-tune >=0.1.1
    - r-workflows >=0.1.2
    - r-yardstick >=0.0.7

test:
  commands:
    - $R -e "library('tidymodels')"           # [not win]
    - "\"%R%\" -e \"library('tidymodels')\""  # [win]

about:
  home: https://github.com/tidymodels/tidymodels
  license: GPL-3.0-only
  summary: The tidy modeling "verse" is a collection of packages for  modeling and statistical analysis that share the underlying design philosophy, grammar, and data structures of the tidyverse.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidymodels
# Title: Easily Install and Load the 'Tidymodels' Packages
# Version: 0.0.3
# Authors@R: c( person(given = "Max",    family = "Kuhn",    email = "max@rstudio.com",      role = c("aut", "cre")), person(given = "Hadley", family = "Wickham", email = "hadley@rstudio.com",   role = c("aut")), person("RStudio", role = c("cph", "fnd")) )
# Description: The tidy modeling "verse" is a collection of packages for  modeling and statistical analysis that share the underlying design philosophy, grammar, and data structures of the tidyverse.
# License: GPL-3 | file LICENSE
# URL: https://github.com/tidymodels/tidymodels
# BugReports: https://github.com/tidymodels/tidymodels/issues
# Depends: R (>= 3.1)
# Imports: broom (>= 0.5.2), cli (>= 1.1.0), crayon (>= 1.3.4), dials (>= 0.0.3), dplyr (>= 0.8.3), ggplot2 (>= 3.2.1), infer (>= 0.5.0), magrittr (>= 1.5), parsnip (>= 0.0.3.1), pillar (>= 1.4.2), purrr (>= 0.3.2), recipes (>= 0.1.7), rlang (>= 0.4.0), rsample (>= 0.0.5), rstudioapi (>= 0.10), tibble (>= 2.1.3), tidytext (>= 0.2.2), tidypredict (>= 0.4.3), tidyposterior (>= 0.0.2), yardstick (>= 0.0.4)
# Suggests: covr, knitr, rmarkdown, testthat, xml2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-04 21:11:00 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-04 23:00:02 UTC
