{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidymodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidymodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidymodels/tidymodels_{{ version }}.tar.gz
  sha256: f3fd331340fcc39581bd8e2653424b46600ade6307cdb39b13d91f05e64d7dc0

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=1.0.0
    - r-cli >=3.3.0
    - r-conflicted >=1.1.0
    - r-dials >=1.0.0
    - r-dplyr >=1.0.9
    - r-ggplot2 >=3.3.6
    - r-hardhat >=1.2.0
    - r-infer >=1.0.2
    - r-modeldata >=1.0.0
    - r-parsnip >=1.0.0
    - r-purrr >=0.3.4
    - r-recipes >=1.0.1
    - r-rlang >=1.0.3
    - r-rsample >=1.0.0
    - r-rstudioapi >=0.13
    - r-tibble >=3.1.7
    - r-tidyr >=1.2.0
    - r-tune >=1.0.0
    - r-workflows >=1.0.0
    - r-workflowsets >=1.0.0
    - r-yardstick >=1.0.0
  run:
    - r-base
    - r-broom >=1.0.0
    - r-cli >=3.3.0
    - r-conflicted >=1.1.0
    - r-dials >=1.0.0
    - r-dplyr >=1.0.9
    - r-ggplot2 >=3.3.6
    - r-hardhat >=1.2.0
    - r-infer >=1.0.2
    - r-modeldata >=1.0.0
    - r-parsnip >=1.0.0
    - r-purrr >=0.3.4
    - r-recipes >=1.0.1
    - r-rlang >=1.0.3
    - r-rsample >=1.0.0
    - r-rstudioapi >=0.13
    - r-tibble >=3.1.7
    - r-tidyr >=1.2.0
    - r-tune >=1.0.0
    - r-workflows >=1.0.0
    - r-workflowsets >=1.0.0
    - r-yardstick >=1.0.0

test:
  commands:
    - $R -e "library('tidymodels')"           # [not win]
    - "\"%R%\" -e \"library('tidymodels')\""  # [win]

about:
  home: https://github.com/tidymodels/tidymodels
  license: MIT
  summary: The tidy modeling "verse" is a collection of packages for  modeling and statistical analysis that share the underlying design philosophy, grammar, and data structures of the tidyverse.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidymodels
# Title: Easily Install and Load the 'Tidymodels' Packages
# Version: 0.0.3
# Authors@R: c( person(given = "Max",    family = "Kuhn",    email = "max@rstudio.com",      role = c("aut", "cre")), person(given = "Hadley", family = "Wickham", email = "hadley@rstudio.com",   role = c("aut")), person("RStudio", role = c("cph", "fnd")) )
# Description: The tidy modeling "verse" is a collection of packages for  modeling and statistical analysis that share the underlying design philosophy, grammar, and data structures of the tidyverse.
# License: GPL-3 | file LICENSE
# URL: https://github.com/tidymodels/tidymodels
# BugReports: https://github.com/tidymodels/tidymodels/issues
# Depends: R (>= 3.1)
# Imports: broom (>= 0.5.2), cli (>= 1.1.0), crayon (>= 1.3.4), dials (>= 0.0.3), dplyr (>= 0.8.3), ggplot2 (>= 3.2.1), infer (>= 0.5.0), magrittr (>= 1.5), parsnip (>= 0.0.3.1), pillar (>= 1.4.2), purrr (>= 0.3.2), recipes (>= 0.1.7), rlang (>= 0.4.0), rsample (>= 0.0.5), rstudioapi (>= 0.10), tibble (>= 2.1.3), tidytext (>= 0.2.2), tidypredict (>= 0.4.3), tidyposterior (>= 0.0.2), yardstick (>= 0.0.4)
# Suggests: covr, knitr, rmarkdown, testthat, xml2
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-04 21:11:00 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-04 23:00:02 UTC
