{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidymodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidymodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidymodels/tidymodels_{{ version }}.tar.gz
  sha256: aea6df3c32b31dd79776c529c87fe16fb9dcc5b157b993b449b41dd3a57657f6

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=1.0.9
    - r-cli >=3.6.5
    - r-conflicted >=1.2.0
    - r-dials >=1.4.2
    - r-dplyr >=1.1.4
    - r-ggplot2 >=3.5.2
    - r-hardhat >=1.4.2
    - r-infer >=1.0.9
    - r-modeldata >=1.5.1
    - r-parsnip >=1.3.2
    - r-purrr >=1.1.0
    - r-recipes >=1.3.1
    - r-rlang >=1.1.6
    - r-rsample >=1.3.1
    - r-rstudioapi >=0.17.1
    - r-tailor >=0.1.0
    - r-tidyr >=1.3.1
    - r-tune >=1.3.0
    - r-workflows >=1.3.0
    - r-workflowsets >=1.1.1
    - r-yardstick >=1.3.2
  run:
    - r-base
    - r-broom >=1.0.9
    - r-cli >=3.6.5
    - r-conflicted >=1.2.0
    - r-dials >=1.4.2
    - r-dplyr >=1.1.4
    - r-ggplot2 >=3.5.2
    - r-hardhat >=1.4.2
    - r-infer >=1.0.9
    - r-modeldata >=1.5.1
    - r-parsnip >=1.3.2
    - r-purrr >=1.1.0
    - r-recipes >=1.3.1
    - r-rlang >=1.1.6
    - r-rsample >=1.3.1
    - r-rstudioapi >=0.17.1
    - r-tailor >=0.1.0
    - r-tidyr >=1.3.1
    - r-tune >=1.3.0
    - r-workflows >=1.3.0
    - r-workflowsets >=1.1.1
    - r-yardstick >=1.3.2

test:
  commands:
    - $R -e "library('tidymodels')"           # [not win]
    - "\"%R%\" -e \"library('tidymodels')\""  # [win]

about:
  home: https://github.com/tidymodels/tidymodels
  license: MIT
  summary: The tidy modeling "verse" is a collection of packages for  modeling and statistical analysis that share the underlying design philosophy, grammar, and data structures of the tidyverse.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
