appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dxtp1NggVChTe3OZAggplCsLQKxr/V6DQn29K4eFkyzobt33uQEm4lQMHSiwbQp1Smkf14JrfvNnhyqKDiVxjvz88Zz21C026XI9WR2PaaRUSeSRGF4GJv6w6Z11+kjWP6V8xRd+E2I1lvazb0k28BB6ELF0cZLFZ4FxfYbCEgqnWnW59yXGIs/wvELH8s2u72yv3WE9ZCA4oUtF6Vyi2sUKRZV/HiVEpHxyEVhozczX1h7xJknTzvONupEAznsIigrnRA4GTjkg3Of5d8EiYiKZvNQ0yNCejHnyKY7iCWzlrqJBxonWIShQDbCQp6XmanKzhxiLg8qYaxbt/7pi/b6L5z+AGL3f1yjY040O7CxZWt7JqbSmFNL5r/Wxy4kcWAsC5HMrszeD6l/sYnArOgxi3p0FPXF/QW4lGczCmab9pdhsvqC1QPFo6ARAG75l9iTMw2kUlQzB+/7P6tHklph4jkjoYBmKz4CuP+dpU3tKdLdjJzrbyfhR2LhmrALk/ZDB1V8OwDhc1jttWPi0mdCEKMB+VM7XRwG6k1ohpUN1OxLb9LUFR5KmIs+lwh9lQLOWnIfkgRBRPgqKTjHEL+LpsNaN48DBVQwooSLYhsrZmROdfKVw2osSieynOjIgczACHssM6Tpn77cW82Zg2SEBmgQnm2zEFg8SZgf9Hl0=}
bot:
  automerge: true
